### ISSUE TITLE
Add a way to delete date and time

### ISSUE THREAD

**Issue by AAKrasnova** [sadevana/best-to-do-ever#15]
Now it's impossible to clear the date or time from the task. There should be opportunity. 
Requirement was in #11 

**From**: Testing @AAKrasnova

**Comment by dchicherin** [comment]
Clearing is done by pressing on symbol that appears inside the field when editing 

![Image](https://github.com/sadevana/best-to-do-ever/assets/32911387/7b0cbf6e-1e31-4a29-9b88-44e542d660bd)

**Comment by AAKrasnova** [comment]
When deleting date time the position in the quest list does not change.
![Image](https://github.com/sadevana/best-to-do-ever/assets/10058916/57362e72-54e8-4f84-aa40-35d9a58f9525)
*I'll share GIF in TG

**Comment by AAKrasnova** [comment]
**Tested**: Done. ✅
