### ISSUE TITLE
Provide faster way to pick current date as deadline

### ISSUE THREAD

**Issue by AAKrasnova** [sadevana/best-to-do-ever#18]
To choose the current date user needs to 
1) click Date
2) choose any date that is not current
3) choose the current date
4) click done

Let's provide faster way to pick current date as deadline

**From**: Testing @AAKrasnova

**Comment by dchicherin** [comment]
on edit set default date picker date to one chosen

**Comment by AAKrasnova** [comment]
From: Testing @AAKrasnova
OK

**Comment by AAKrasnova** [comment]
Doesn't need to be documented
