### ISSUE TITLE
Basic task adding logic

### ISSUE THREAD

**Issue by AAKrasnova** [sadevana/best-to-do-ever#4]
### Wireframe
![image](https://github.com/sadevana/best-to-do-ever/assets/10058916/f0af4a44-991f-4c99-befb-f5dca5feabc6)

### Interface behavior
Only the task name is not nullable
The date is nullable, but if a user opens the date picker, the default is today.
The date is DD.MM.YY format
Time is nullable, but if a user opens the time picker, the default is 23:59.
Time is HH:mm format
Gold default is 5
Gold accepts int from 0 to 1 000 000 000
OK button saves tasks (adds new or saves changes)
OK button is floating above form fields but if a user scrolls to the end it has space to fit in.
Cancel button floating together with OK button
Cancel button closes screen without saving changes
User can cancel adding task by using standard iOS button "Back"

### How user enters
User enters the screen by pressing the big "plus" button

**Comment by AAKrasnova** [comment]
We need cancel button.  updated.
![image](https://github.com/sadevana/best-to-do-ever/assets/10058916/f1d80fbe-17db-455e-b6c1-13e66baf9c9d)

**Comment by dchicherin** [comment]
Finished basic task creation

**Comment by AAKrasnova** [comment]
I changed requirement about max gold: 1 000 000 000  -> 9 999 999 999 to match the implementation

**Comment by AAKrasnova** [comment]
DELETED "OK button is floating above form fields but if a user scrolls to the end it has space to fit in."

**Comment by AAKrasnova** [comment]
Documented: https://github.com/sadevana/best-to-do-ever/blob/main/docs/App/Screens%20and%20Dialogues.md
