### ISSUE TITLE
Icons for quests

### ISSUE THREAD

**Issue by dchicherin** [sadevana/best-to-do-ever#43]
### Reality pack: 
**Checklist**: A small clipboard with a checklist. Ideal for tasks that involve multiple steps or for general tasks.

**Bulb**: Represents ideas, creativity, or inspiration-related tasks.

**Home**: Suitable for home-related tasks such as cleaning, gardening, or home maintenance.

**Briefcase**: Represents work or business-related tasks.

**Book**: Suitable for reading, studying, or other educational tasks.

**Shopping Cart**: For shopping or errand-related tasks.

**Fitness Dumbbell or Shoe**: Represents exercise or health-related tasks.

**Laptop or Computer**: For tech or digital tasks, or perhaps for reminding users to send emails or finish online courses.

**Clock or Hourglass**: For time-bound or urgent tasks.

**Heart**: Tasks related to self-care, relaxation, or time spent with loved ones.

### Adventure pack:
**Map or Compass**: Representing tasks that require direction or planning.

**Backpack**: Suitable for tasks related to preparations or gathering resources.

**Mountain Peak**: For high-priority or challenging tasks that require effort, akin to reaching the summit.

**Campfire**: Tasks related to relaxation, breaks, or downtime.

**Tent**: For tasks that require a longer time to complete or multi-day commitments.

**Treasure Chest:** For rewarding or high-value tasks.

**Binoculars**: Tasks that require focus or foreseeing something in the future.

**Ship's Wheel or Anchor**: For tasks related to steering the course or grounding oneself.

**Sword or Shield**: Representing tasks that require defense or fighting off challenges, perhaps even tasks that deal with conflict resolution.

**Magic Potion or Scroll**: Tasks related to learning, acquiring new skills, or magical solutions.

**Comment by dchicherin** [comment]
This will require to implement a more complicated way of choosing icon. I'd say we need a short list of 6-8 for now unless we want to implement picking system
Also a question for @Vinylnd - is it easy to find/implement this many icons? Maybe we should just copy an entire set somewhere?

**Comment by dchicherin** [comment]
Done with 6 icons for now, chosen from bar

**Comment by AAKrasnova** [comment]
**Tested**: Done. ✅
![Image](https://github.com/sadevana/best-to-do-ever/assets/10058916/a7af58d1-a0de-4156-a3d9-cfbd70effa21)
