### ISSUE TITLE
Basic task card on home screen

### ISSUE THREAD

**Issue by AAKrasnova** [sadevana/best-to-do-ever#6]
### Wireframe
![image](https://github.com/sadevana/best-to-do-ever/assets/10058916/a29fc13e-e398-4bb9-8109-491c5a269a26)

### Interface logic
"tick" button should change its appearance based on task completion ([Task: done])
When "tick" button is pressed task should change its done status to the opposite: done-> undone; undone -> done.
> Reward for task completion should be added
> Reward for undoing task should be deducted

More on it in #7

time\date ([Task:due date]) is displayed if it's specified
time is  HH:mm format
date is in DD.MM format

If the user taps the card, the Edit task screen (#8) opens.

### How user enters
The user sees task cards on the Home screen

**Comment by AAKrasnova** [comment]
**DELETED**:
"arrow_down button is displayed if there is a description
If the arrow_down button is pressed, the description ([Task: description]) is displayed under the title and the reward"

**Comment by AAKrasnova** [comment]
@dchicherin Confirm that we refused these ideas:

- "title of the task should display fully even if it takes multiple lines"
- "gold reward is displayed if it's more than 0"

**Comment by dchicherin** [comment]
Yeah, design becomes awkward if we do those

**Comment by AAKrasnova** [comment]
OK

**Comment by AAKrasnova** [comment]
Doc: https://github.com/sadevana/best-to-do-ever/commit/fac6c96e7383580ace0066f107f4cb33d145f130
