### ISSUE TITLE
Task editing and deleting logic

### ISSUE THREAD

**Issue by AAKrasnova** [sadevana/best-to-do-ever#8]
Edit an existing task's details.
Delete a task from the list.

### Wireframe
![Image](https://user-images.githubusercontent.com/10058916/263829466-c89fb2d1-d8e4-4020-a035-3500887645f1.png)

Identical to the Create Task screen but with a fixed-placed red "Delete" button at the end of the form

### Interface logic
Form fields logic identical to the Create Task #4.
Cancel button cancels changes without saving
User can cancel editing task by using standard iOS button "Back"
Delete button deletes tasks without awarding\deducting gold.

> ??? TODO: ask user before deleting???

OK button saves changes to the task if they are valid
If changes are invalid, show an error message

 ### How user enters
A user enters the Edit task screen by tapping the task card in to-do list

**Comment by AAKrasnova** [comment]
Q: Will we additionally ask users before deleting the quest?

**Comment by dchicherin** [comment]
I thought about it, maybe we should

**Comment by AAKrasnova** [comment]
WEEKLY: Yes, let's show a confirmation window, for now: system alert, not girl-dependent

**Comment by AAKrasnova** [comment]
**Tested**: Done. ✅
